---
- hosts: "unifi" #"nodes,master"
  become: true
  become_user: root
  tasks:
    - name: Install Docker
      script: ./scripts/docker-install.sh --creates home/joel/installations/installed-docker.txt
      register: output
    - debug: var=output.stdout_lines
    - name: Restart Server
      reboot:
   
