---
- hosts: all
  strategy: free
  gather_facts: false
  connection: local
  tasks:
    - name: ping test
      shell: ping -c 5 -w 10 -D {{ ansible_host }}
      # delegate_to: localhost
      ignore_errors: true