---
- hosts: all
  become: true
  become_user: root
  # sudo: true
  tasks:
    - name: updates a server
      apt: 
        update_cache: yes
    - name: upgrade a server
      apt: 
        upgrade: dist
    - name: autoremove unnecessary packages
      apt: 
        autoremove: yes
    - name: autoclean system
      apt: 
        autoclean: yes
