---
- hosts: master
  tasks:
    - name: Deploy Flannel and MetalLB
      block:     
        - name: Make .kube dir
          raw: mkdir -p $HOME/.kube
        - name: cp admin.conf
          raw: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        - name: chown admin.conf
          raw: sudo chown $(id -u):$(id -g) $HOME/.kube/config
        - name: Copy Flannel yaml
          ansible.builtin.copy:
            src: ./kube-flannel.yaml
            dest: /kube-flannel.yaml
        - name: Setup flannel
          raw: kubectl apply -f /kube-flannel.yaml
        - name: Copy MetalLB yaml
          ansible.builtin.copy:
            src: ./metallb.yaml
            dest: ~/metallb.yaml
        - name: Copy MetalLB Config yaml
          ansible.builtin.copy:
            src: ./metallbconfigmap.yaml
            dest: ~/metallbconfigmap.yaml
        - name: Setup MetalLB
          raw: kubectl apply -f ~/metallb.yaml
        - name: Setup MetalLB Config Map
          raw: kubectl apply -f ~/metallbconfigmap.yaml
        - name: Restart CoreDNS
          raw: kubectl rollout restart deployment coredns --namespace kube-system